### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Gy-Hu** [YosysHQ/imctk#23]
Hi, I try to run this project by executing:
1. git submodule update --init --recursive
2. cargo build --release

However, I encounter this error, how to fix it?:

```
   Compiling imctk-abc v0.1.0 (/data/guangyuh/coding_env/imctk/abc)
error[E0425]: cannot find function `imctk_abc_glucose2_init` in crate `abc`
  --> abc/src/sat/glucose2.rs:85:28
   |
85 |             let ptr = abc::imctk_abc_glucose2_init();
   |                            ^^^^^^^^^^^^^^^^^^^^^^^ not found in `abc`

error[E0425]: cannot find function `imctk_abc_glucose2_set_incremental_mode` in crate `abc`
  --> abc/src/sat/glucose2.rs:86:18
   |
86 |             abc::imctk_abc_glucose2_set_incremental_mode(ptr);
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `abc`

error[E0425]: cannot find function `imctk_abc_glucose2_set_jftr` in crate `abc`
  --> abc/src/sat/glucose2.rs:87:18
   |
87 |             abc::imctk_abc_glucose2_set_jftr(ptr, Mode::JFTR);
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `abc`

error[E0425]: cannot find function `imctk_abc_glucose2_release` in crate `abc`
```

**Comment by jix** [comment]
The error indicates that the submodule in `abc-sys/abc` is not at the right commit. A few weeks ago there was a brief period where I had merged an inconsistent commit to `main` but that was resolved as soon as I noticed, if your local `main` branch happens to be at that commit you might need to pull the latest changes first. In any case I cannot reproduce this error with my local clone nor with a fresh clone.

Do you still get this error if you perform a fresh clone?

Also note that imctk is currently still a very early work in progress, so just to set expectations, even if you get it to compile, it might not be useful for anything in particular yet.

**Comment by Gy-Hu** [comment]
Thank you, the refresh clone resolved the issue for now. I also noticed that this is a very early work in progress. I just want to take a look and learn something new here :)
